#!/usr/bin/env python3
"""Generate starter/ and solution/ from the canonical tree in src/.

src/ is the single source of truth. Attendee-facing trees are derived, never hand-edited,
so they cannot drift. Regions look like:

    // >>> TODO 1 | what the attendee must do | STUB: throw new NotImplementedException("...");
    ...canonical implementation...
    // <<< TODO 1

starter/  replaces each region with its stub, so it compiles but does nothing yet.
solution/ keeps the implementation and strips the marker lines.

Usage:
  generate-starter.py           regenerate starter/ and solution/
  generate-starter.py --check   fail if the committed trees differ from a fresh generation
"""

import filecmp
import re
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

COPY = [
    "Directory.Build.props",
    "Directory.Packages.props",
    "Workshop.slnx",
    ".env.example",
    "src",
    "tests",
    # CP-03's deterministic Gather tests and command use this approved, swappable corpus. Keep it
    # in the generated attendee trees so a starter checkout is self-contained.
    "workshop/data",
]
SKIP_DIRS = {"bin", "obj", "artifacts", ".vs", ".idea"}
SKIP_FILES = set()

OPEN = re.compile(r"^(\s*)//\s*>>> TODO (\d+)\s*\|\s*(.*?)\s*\|\s*STUB:\s*(.*)$")
CLOSE = re.compile(r"^\s*//\s*<<< TODO (\d+)\s*$")


def transform(text, mode):
    out, skipping, found = [], None, []
    for line in text.splitlines():
        opened = OPEN.match(line)
        if opened:
            indent, number, description, stub = opened.groups()
            found.append(int(number))
            skipping = number
            if mode == "starter":
                out.append(f"{indent}// TODO {number}: {description}")
                out.append(f"{indent}{stub}")
            continue
        closed = CLOSE.match(line)
        if closed and skipping == closed.group(1):
            skipping = None
            continue
        if skipping and mode == "starter":
            continue
        out.append(line)
    if skipping:
        raise SystemExit(f"unclosed TODO region {skipping}")
    return "\n".join(out) + "\n", found


def build(target: Path):
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    mode = target.name
    todos = []

    for entry in COPY:
        source = ROOT / entry
        if source.is_file():
            shutil.copy2(source, target / entry)
            continue
        for path in sorted(source.rglob("*")):
            if any(part in SKIP_DIRS for part in path.relative_to(ROOT).parts):
                continue
            relative = path.relative_to(ROOT)
            if relative.as_posix() in SKIP_FILES:
                continue
            destination = target / relative
            if path.is_dir():
                destination.mkdir(parents=True, exist_ok=True)
            elif path.suffix == ".cs":
                destination.parent.mkdir(parents=True, exist_ok=True)
                rewritten, found = transform(path.read_text(), mode)
                destination.write_text(rewritten)
                todos.extend((number, relative.as_posix()) for number in found)
            else:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, destination)

    (target / "artifacts").mkdir(exist_ok=True)
    (target / "artifacts" / ".gitkeep").write_text("")
    (target / "README.md").write_text(readme(mode, sorted(set(todos))))
    return sorted(set(todos))


def readme(mode, todos):
    listed = "\n".join(f"- **TODO {number}** — `{path}`" for number, path in todos)
    if mode == "starter":
        return f"""# Starter — Small Models, Sharp Jobs

Generated from the canonical `src/` tree. Do not edit this file by hand.

You will complete {len(todos)} crash-workflow TODOs. The project compiles now; each unfinished
typed model step returns no result, so its `run` command takes the intentional caution branch.

{listed}

## Loop

```bash
dotnet test
dotnet run --project src/Workshop.App -- gather --term intersection
dotnet run --project src/Workshop.App -- run --term intersection   # done when this exits 0 with gate: Supported
```

`dotnet test` is already green: the TODOs live in `Workshop.App`, which those tests do not reach. The
exit code of `run` is the gate; `WORKSHOP_LOCAL_MODEL=1 dotnet test` checks it with a model.

Stuck? The finished code for every TODO is in `../solution/`.
"""
    return f"""# Solution — Small Models, Sharp Jobs

Generated from the canonical `src/` tree with the TODO markers stripped. Do not edit by hand.

Completed here:

{listed}

```bash
dotnet test
dotnet run --project src/Workshop.App -- run
```
"""


def main():
    check = "--check" in sys.argv
    if check:
        with tempfile.TemporaryDirectory() as temporary:
            failures = []
            for name in ("starter", "solution"):
                fresh = Path(temporary) / name
                build(fresh)
                committed = ROOT / name
                if not committed.exists():
                    failures.append(f"{name}/ has not been generated")
                    continue
                if differences(fresh, committed):
                    failures.append(f"{name}/ differs from a fresh generation: {differences(fresh, committed)}")
            if failures:
                print("DRIFT DETECTED")
                for failure in failures:
                    print(f"  {failure}")
                return 1
            print("no drift: starter/ and solution/ match a fresh generation of src/")
            return 0

    for name in ("starter", "solution"):
        todos = build(ROOT / name)
        print(f"generated {name}/ with {len(todos)} TODO region(s)")
    return 0


def differences(left: Path, right: Path):
    comparison = filecmp.dircmp(left, right, ignore=list(SKIP_DIRS))
    found = []

    def walk(node, prefix=""):
        for name in node.left_only:
            found.append(f"missing in committed: {prefix}{name}")
        for name in node.right_only:
            if name in SKIP_DIRS:
                continue
            found.append(f"unexpected in committed: {prefix}{name}")
        for name in node.diff_files:
            found.append(f"content differs: {prefix}{name}")
        for name, child in node.subdirs.items():
            if name not in SKIP_DIRS:
                walk(child, f"{prefix}{name}/")

    walk(comparison)
    return found


if __name__ == "__main__":
    raise SystemExit(main())
